excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
line_length: 150
identifier_name:
 excluded: id